#!/bin/bash
ROMDIR='/home/pi/RetroPie/roms'
BAKFILE='/home/pi/.favorites/current.zip'
IFS=$'\n'
SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
RESTORESCRIPT="$SCRIPTDIR/fav_restore_one"

cd "$ROMDIR"
unzip -o "$BAKFILE"

for file in `find $ROMDIR -type f -name "gamelist.xml"`
do
	dir="$(dirname $file)"
	echo -n Processing $dir ... 
	cd $dir
	python "$RESTORESCRIPT"
	rm -f ./.games__
	cd $ROMDIR
done
echo "Restoration Complete !"
